<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array (
		'key' => 'group_58f927e2e9851',
		'title' => 'SF Custom Page Builder',
		'fields' => array (
			array (
				'key' => 'field_58f927f3f1f93',
				'label' => 'Custom Page Builder',
				'name' => 'custom_page_editor',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'button_label' => 'Add Section',
				'min' => '',
				'max' => '',
				'layouts' => array (
					array (
						'key' => '58f927f8e0768',
						'name' => 'body_copy',
						'label' => 'Body Copy',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_5907b5541ffde',
								'label' => 'Clone',
								'name' => 'clone',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'clone' => array (
									0 => 'group_5907b50e01349',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					array (
						'key' => '5914d0a0a37e9',
						'name' => 'insert_custom_section',
						'label' => 'Insert Custom Section',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_5914d0bca37ea',
								'label' => 'Section Name',
								'name' => 'section_name',
								'type' => 'text',
								'instructions' => 'Insert the name of the Custom Section you wish to place here.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_taxonomy',
					'operator' => '==',
					'value' => 'sf_tools:page-builder',
				),
			),
		),
		'menu_order' => -5,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'the_content',
		),
		'active' => 1,
		'description' => '',
		'modified' => 1494896703,
	));

	acf_add_local_field_group(array (
		'key' => 'group_5914bb7e87d28',
		'title' => 'Body Copy',
		'fields' => array (
			array (
				'key' => 'field_5914bbb2d66c8',
				'label' => 'Body Copy',
				'name' => 'body_copy',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'clone' => array (
					0 => 'group_5907b50e01349',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_taxonomy',
					'operator' => '==',
					'value' => 'sf_tools:body-copy',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array (
			0 => 'the_content',
		),
		'active' => 1,
		'description' => '',
		'modified' => 1494896568,
	));

	acf_add_local_field_group(array (
		'key' => 'group_58d9595d5d72e',
		'title' => 'BYU Header',
		'fields' => array (
			array (
				'key' => 'field_58d95135651d8',
				'label' => 'BYU Site Title',
				'name' => 'site_title',
				'type' => 'text',
				'instructions' => 'This field will populate the site title across all pages in the top BYU ribbon.
(ie. The title in the top left, after BYU.)',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Site Name',
				'placeholder' => 'Type here',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58d95e87eb1de',
				'label' => 'Display BYU Header Menu',
				'name' => 'display_byu_header_menu',
				'type' => 'true_false',
				'instructions' => 'Check this box if you would like a sub-navigation menu within the header, under the BYU ribbon.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Display Menu',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array (
				'key' => 'field_58d95f0f56ae9',
				'label' => 'BYU Header Menu',
				'name' => 'byu_header_menu',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58d95e87eb1de',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'button_label' => 'Add Menu Item',
				'min' => 1,
				'max' => 16,
				'layouts' => array (
					array (
						'key' => '58d95f1f8f3a4',
						'name' => 'menu_link',
						'label' => 'Menu Link',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_58d961a022a15',
								'label' => 'Text',
								'name' => 'text',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58e7c29c6e603',
								'label' => 'Type',
								'name' => 'type',
								'type' => 'radio',
								'instructions' => 'Select the type of link',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'internal' => 'Internal',
									'external' => 'External',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'Internal',
								'layout' => 'vertical',
								'return_format' => 'value',
							),
							array (
								'key' => 'field_58d961b022a16',
								'label' => 'Url',
								'name' => 'url',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_58e7c29c6e603',
											'operator' => '==',
											'value' => 'external',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
							),
							array (
								'key' => 'field_58e7c36c44e33',
								'label' => 'Relative Url',
								'name' => 'relative_url',
								'type' => 'text',
								'instructions' => 'Include only the part of the url that comes after the domain name.<br>
ie. if you want to link to the root of the site just enter "/" as the link.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_58e7c29c6e603',
											'operator' => '==',
											'value' => 'internal',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '/',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),
			),
			array (
				'key' => 'field_591363bf7dba2',
				'label' => 'Display Login',
				'name' => 'display_login',
				'type' => 'true_false',
				'instructions' => 'Check this box to display the login or logout option in the header',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array (
				'key' => 'field_59135149e9001',
				'label' => 'Display Search',
				'name' => 'display_search',
				'type' => 'true_false',
				'instructions' => 'Check this box to display the search bar in the header',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array (
				'key' => 'field_591354510cd11',
				'label' => 'Select Type Of Header',
				'name' => 'select_type_of_header',
				'type' => 'radio',
				'instructions' => 'Check the box of the type of header you would like to display. If it contains a sub-title or super-title a new field will appear to fill with your chosen text',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'header_only' => 'Header only',
					'header_with_sub-title' => 'Header with sub-title',
					'header_with_super-title' => 'Header with super-title',
					'header_with_ italicized_sub-title' => 'Header with Italicized sub-title',
					'header_with_ italicized_super-title' => 'Header with Italicized super-title',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_5913571ec8d52',
				'label' => 'Sub-title or super-title text',
				'name' => 'sub-title_or_super-title_text',
				'type' => 'text',
				'instructions' => 'If you have selected to use a sub-title or super-title enter your text here.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_591354510cd11',
							'operator' => '==',
							'value' => 'header_with_sub-title',
						),
					),
					array (
						array (
							'field' => 'field_591354510cd11',
							'operator' => '==',
							'value' => 'header_with_super-title',
						),
					),
					array (
						array (
							'field' => 'field_591354510cd11',
							'operator' => '==',
							'value' => 'header_with_ italicized_sub-title',
						),
					),
					array (
						array (
							'field' => 'field_591354510cd11',
							'operator' => '==',
							'value' => 'header_with_ italicized_super-title',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'site_options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1494446078,
	));

	acf_add_local_field_group(array (
		'key' => 'group_5907b50e01349',
		'title' => 'Template - Body Copy',
		'fields' => array (
			array (
				'key' => 'field_5914bce6bb3dc',
				'label' => 'Body Copy',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_58f92804f1f94',
				'label' => 'HTML Body Copy',
				'name' => 'html_body_copy',
				'type' => 'textarea',
				'instructions' => 'Html requires using html semantics such as \'p\' for paragraphs and \'h2\' for headings and \'a\' for anchors. If possible use this, It provides much cleaner HTML to the frontend.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5907b68f6bf04',
							'operator' => '==',
							'value' => 'html',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '<h1>Reserve h1 for the page title itself<h1>

<p>This is a sample paragraph with a <a href="https://google.com">link to google</a>.
 You can <b>bold like this</b> and use <i>italics like this</i>.</p>

<h2>Continue Using (NOTE: Typically Body Copy headings start with h2)</h2>

<h3>Progressively Smaller Headings</h3>

<h4>To Nest Sub Sections</h4>

<h5>Use the Same Number</h5>

<h5>For Sibling Sections</h5>

<h6>With the smallest being an h6</h6>

<p>For more information refer to <a href="https://www.w3schools.com/html/html_basic.asp">w3schools</a>.</p>',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 12,
				'new_lines' => '',
			),
			array (
				'key' => 'field_5907b8ec71da9',
				'label' => 'Wysiwyg Body Copy',
				'name' => 'wysiwyg_body_copy',
				'type' => 'wysiwyg',
				'instructions' => 'Wysiwyg allows you to use a nice interface similar to a word document to edit your text. Easier to use without basic coding knowledge, but creates messy HTML for the frontend.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5907b68f6bf04',
							'operator' => '==',
							'value' => 'wysiwyg',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 0,
				'delay' => 0,
			),
			array (
				'key' => 'field_58f92930f1f95',
				'label' => 'Body Extras',
				'name' => 'body_extras',
				'type' => 'flexible_content',
				'instructions' => 'For best results enter images, videos, pull quotes, and other things here. You will be allowed finer control over the placement and size. Also, placing them here instead of in the wysiwyg editor allows these elements to be much more responsive.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array (
					'58f9293fa5ed8' => array (
						'key' => '58f9293fa5ed8',
						'name' => 'image',
						'label' => 'Image',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_590918aa5f76c',
								'label' => 'Image',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_58f92a23f1f98',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array (
								'key' => 'field_58f929bdf1f97',
								'label' => 'Vertical Position',
								'name' => 'vertical_position',
								'type' => 'number',
								'instructions' => 'Choose the paragraph Number this Image is supposed to appear after. If number is invalid or too large the image will appear at the very end of the copy.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 0,
								'max' => '',
								'step' => 1,
							),
							array (
								'key' => 'field_5919fc072455d',
								'label' => 'Width and Horizontal Position',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_center',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_5909247e4766c',
								'label' => 'Clone Standard Center Positioning',
								'name' => 'clone_standard_center_positioning',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'clone' => array (
									0 => 'group_5909216abef06',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
							),
							array (
								'key' => 'field_5919fc1d2455e',
								'label' => 'Width and Horizontal Position',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_left',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_59092cfb02c63',
								'label' => 'Clone Standard Left Positioning',
								'name' => 'clone_standard_left_positioning',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_left',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'clone' => array (
									0 => 'group_59092c731a33d',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'591a05c88ba5c' => array (
						'key' => '591a05c88ba5c',
						'name' => 'youtube_video',
						'label' => 'YouTube Video',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_591a08cb15951',
								'label' => 'YouTube Video',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_591a06018ba5d',
								'label' => 'YouTube Video Code',
								'name' => 'youtube_video_code',
								'type' => 'text',
								'instructions' => 'Enter the code associated with the desired YouTube video. This can be found in any url or link associated with the YouTube video.<br>
ie. Given the url \'https://www.youtube.com/watch?v=tQXr5HE8TLA\' the code is \'tQXr5HE8TLA\'.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_591a07a82b8ce',
								'label' => 'Vertical Position',
								'name' => 'vertical_position',
								'type' => 'number',
								'instructions' => 'Choose the paragraph Number this Image is supposed to appear after. If number is invalid or too large the image will appear at the very end of the copy.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 0,
								'max' => '',
								'step' => 1,
							),
							array (
								'key' => 'field_591a086f3e696',
								'label' => 'Width and Horizontal Position',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_center',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_591a087c3e697',
								'label' => 'Clone Standard Center Positioning',
								'name' => 'clone_standard_center_positioning',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'clone' => array (
									0 => 'group_5909216abef06',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
							),
							array (
								'key' => 'field_591a08973e698',
								'label' => 'Width and Horizontal Position',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_left',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_593884fedd485',
								'label' => 'Clone Standard Left Positioning',
								'name' => 'clone_standard_left_positioning',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_left',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'clone' => array (
									0 => 'group_59092c731a33d',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'593883696b38b' => array (
						'key' => '593883696b38b',
						'name' => 'code_block',
						'label' => 'Code Block',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_593884cedd481',
								'label' => 'Code Block',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_5938838a6b38d',
								'label' => 'Vertical Position',
								'name' => 'vertical_position',
								'type' => 'number',
								'instructions' => 'Choose the paragraph Number this Image is supposed to appear after. If number is invalid or too large the image will appear at the very end of the copy.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 0,
								'max' => '',
								'step' => 1,
							),
							array (
								'key' => 'field_5938839d6b38e',
								'label' => 'Code Block Markup',
								'name' => 'code_block_markup',
								'type' => 'textarea',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'new_lines' => '',
							),
							array (
								'key' => 'field_593884e1dd482',
								'label' => 'Width and Horizontal Position',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_center',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_593884ebdd483',
								'label' => 'Clone Standard Center Positioning',
								'name' => 'clone_standard_center_positioning',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'clone' => array (
									0 => 'group_5909216abef06',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
							),
							array (
								'key' => 'field_593884f8dd484',
								'label' => 'Width and Horizontal Position',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_left',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_591a089d3e699',
								'label' => 'Clone Standard Left Positioning',
								'name' => 'clone_standard_left_positioning',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_left',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'clone' => array (
									0 => 'group_59092c731a33d',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'5941958e27290' => array (
						'key' => '5941958e27290',
						'name' => 'pull_quote',
						'label' => 'Pull Quote',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_5941958e27291',
								'label' => 'Pull Quote',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_5941958e27292',
								'label' => 'Vertical Position',
								'name' => 'vertical_position',
								'type' => 'number',
								'instructions' => 'Choose the paragraph Number this Image is supposed to appear after. If number is invalid or too large the image will appear at the very end of the copy.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 0,
								'max' => '',
								'step' => 1,
							),
							array (
								'key' => 'field_5941958e27293',
								'label' => 'Quote Text',
								'name' => 'quote_text',
								'type' => 'textarea',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'new_lines' => '',
							),
							array (
								'key' => 'field_59419b34baa70',
								'label' => 'Quote Author',
								'name' => 'quote_author',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5941958e27294',
								'label' => 'Width and Horizontal Position',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_center',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_5941958e27295',
								'label' => 'Clone Standard Center Positioning',
								'name' => 'clone_standard_center_positioning',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'clone' => array (
									0 => 'group_5909216abef06',
									1 => 'group_5909216abef06',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
							),
							array (
								'key' => 'field_5941958e27296',
								'label' => 'Width and Horizontal Position',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_left',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_5941958e27297',
								'label' => 'Clone Standard Left Positioning',
								'name' => 'clone_standard_left_positioning',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_left',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'clone' => array (
									0 => 'group_59092c731a33d',
									1 => 'group_59092c731a33d',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'595d4c61ec8c6' => array (
						'key' => '595d4c61ec8c6',
						'name' => 'sidebar',
						'label' => 'Sidebar',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_595d4c61ec8c7',
								'label' => 'Sidebar',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_595d4c61ec8c8',
								'label' => 'Vertical Position',
								'name' => 'vertical_position',
								'type' => 'number',
								'instructions' => 'Choose the paragraph Number this Image is supposed to appear after. If number is invalid or too large the image will appear at the very end of the copy.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => 0,
								'max' => '',
								'step' => 1,
							),
							array (
								'key' => 'field_595d4c61ec8c9',
								'label' => 'Sidebar',
								'name' => 'sidebar',
								'type' => 'textarea',
								'instructions' => 'Enter the HTML code that you would like to have placed in this sidebar.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'new_lines' => '',
							),
							array (
								'key' => 'field_595d4c61ec8cb',
								'label' => 'Width and Horizontal Position',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_center',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_595d4c61ec8cc',
								'label' => 'Clone Standard Center Positioning',
								'name' => 'clone_standard_center_positioning',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'clone' => array (
									0 => 'group_5909216abef06',
									1 => 'group_5909216abef06',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
							),
							array (
								'key' => 'field_595d4c61ec8cd',
								'label' => 'Width and Horizontal Position',
								'name' => '',
								'type' => 'tab',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_left',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'placement' => 'top',
								'endpoint' => 0,
							),
							array (
								'key' => 'field_595d4c61ec8ce',
								'label' => 'Clone Standard Left Positioning',
								'name' => 'clone_standard_left_positioning',
								'type' => 'clone',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_590900beca830',
											'operator' => '==',
											'value' => 'standard_left',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'clone' => array (
									0 => 'group_59092c731a33d',
									1 => 'group_59092c731a33d',
								),
								'display' => 'seamless',
								'layout' => 'block',
								'prefix_label' => 0,
								'prefix_name' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Extra',
				'min' => '',
				'max' => '',
			),
			array (
				'key' => 'field_5914bcfabb3dd',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_5907b68f6bf04',
				'label' => 'Body Copy Entry Type',
				'name' => 'body_copy_entry_type',
				'type' => 'radio',
				'instructions' => 'Choose which type of textual input you would like to use for the body copy.<br>
<b>NOTE:</b> If using a wysiwyg editor, resist the temptation to place images and similar elements directly into the text editor! This proves problematic with responsiveness and making the site mobile friendly. Please use the \'extras\' section to include images and similar elements.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'wysiwyg' => 'Wysiwyg',
					'html' => 'HTML',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'wysiwyg',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_590900beca830',
				'label' => 'Body Copy Style Type',
				'name' => 'body_copy_style_type',
				'type' => 'radio',
				'instructions' => 'Select a preset for the styling of the body copy',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'standard_center' => 'Standard Center',
					'standard_left' => 'Standard Left (Under Construction)',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'standard_center',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 0,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_5909216abef06',
		'title' => 'Template - Body Copy - Positioning and Sizing - Standard Center',
		'fields' => array (
			array (
				'key' => 'field_5909190e5f76d',
				'label' => 'Formatting Method',
				'name' => 'formatting_method',
				'type' => 'radio',
				'instructions' => 'Choose the method you would like to use. Presets are the most common and easy to use. Manual is for very specific control, and is not for the faint of heart. :)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'preset' => 'Preset',
					'preset_extended' => 'Preset Extended',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'preset',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_590919a65f76e',
				'label' => 'Standard Center Presets',
				'name' => 'standard_center_presets',
				'type' => 'radio',
				'instructions' => 'Choose the preset you would like to use.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5909190e5f76d',
							'operator' => '==',
							'value' => 'preset',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'text_width' => 'Text Width',
					'medium_inset_right' => 'Medium Inset Right',
					'medium_inset_left' => 'Medium Inset Left',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_5919fa0f8dc7a',
				'label' => 'Standard Center Presets Extended',
				'name' => 'standard_center_presets_extended',
				'type' => 'radio',
				'instructions' => 'Choose the preset you would like to use.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5909190e5f76d',
							'operator' => '==',
							'value' => 'preset_extended',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'text_width' => 'Text Width',
					'large_inset_right' => 'Large Inset Right',
					'large_outset_right_1' => 'Large Outset Right 1',
					'large_outset_right_2' => 'Large Outset Right 2',
					'large_inset_left' => 'Large Inset Left',
					'large_outset_left_1' => 'Large Outset Left 1',
					'large_outset_left_2' => 'Large Outset Left 2',
					'medium_inset_right' => 'Medium Inset Right',
					'medium_outset_right_1' => 'Medium Outset Right 1',
					'medium_outset_right_2' => 'Medium Outset Right 2',
					'medium_inset_left' => 'Medium Inset Left',
					'medium_outset_left_1' => 'Medium Outset Left 1',
					'medium_outset_left_2' => 'Medium Outset Left 2',
					'small_inset_right' => 'Small Inset Right',
					'small_outset_right_1' => 'Small Outset Right 1',
					'small_outset_right_2' => 'Small Outset Right 2',
					'small_inset_left' => 'Small Inset Left',
					'small_outset_left_1' => 'Small Outset Left 1',
					'small_outset_left_2' => 'Small Outset Left 2',
					'tiny_inset_right' => 'Tiny Inset Right',
					'tiny_outset_right_1' => 'Tiny Outset Right 1',
					'tiny_outset_right_2' => 'Tiny Outset Right 2',
					'tiny_inset_left' => 'Tiny Inset Left',
					'tiny_outset_left_1' => 'Tiny Outset Left 1',
					'tiny_outset_left_2' => 'Tiny Outset Left 2',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 0,
		'description' => '',
		'modified' => 1494875325,
	));

	acf_add_local_field_group(array (
		'key' => 'group_59092c731a33d',
		'title' => 'Template - Body Copy - Positioning and Sizing - Standard Left',
		'fields' => array (
			array (
				'key' => 'field_59092c731f8af',
				'label' => 'Formatting Method',
				'name' => 'formatting_method',
				'type' => 'radio',
				'instructions' => 'Choose the method you would like to use. Presets are the most common and easy to use. Manual is for very specific control, and is not for the faint of heart. :)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'preset' => 'Preset',
					'preset_extended' => 'Preset Extended',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_59092c731f8ca',
				'label' => 'Standard Left Presets',
				'name' => 'standard_left_presets',
				'type' => 'radio',
				'instructions' => 'Choose the preset you would like to use.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_59092c731f8af',
							'operator' => '==',
							'value' => 'preset',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'text_width' => 'Text Width',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_5919fd5d1cec4',
				'label' => 'Standard Left Presets Extended',
				'name' => 'standard_left_presets_extended',
				'type' => 'radio',
				'instructions' => 'Choose the preset you would like to use.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_59092c731f8af',
							'operator' => '==',
							'value' => 'preset_extended',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'text_width' => 'Text Width',
					'another_guy' => 'Another Guy',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 0,
		'description' => '',
		'modified' => 1494875525,
	));

	acf_add_local_field_group(array (
		'key' => 'group_590cda33cdb78',
		'title' => 'Template - Grid - Column Variations',
		'fields' => array (
			array (
				'key' => 'field_590cda48c2cff',
				'label' => 'Grid Column Variations',
				'name' => 'grid_col_variations',
				'type' => 'checkbox',
				'instructions' => 'Select the Column Variations',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'std' => 'Col Standard Width',
					'p5' => 'Col Plus Half',
					'1_gutter' => 'Col Plus 1 Gutter',
					'2_gutter' => 'Col Plus 2 Gutters',
					'1_gutter_1_inner' => 'Col Plus 1 Gutter and 1 Inner',
					'0_gutter_1_inner' => 'Col Plus 1 Inner',
				),
				'allow_custom' => 0,
				'save_custom' => 0,
				'default_value' => array (
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'array',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 0,
		'description' => '',
		'modified' => 1494014762,
	));

	acf_add_local_field_group(array (
		'key' => 'group_5907ae157e336',
		'title' => 'Template - Link',
		'fields' => array (
			array (
				'key' => 'field_5907ae47518cf',
				'label' => 'Link To',
				'name' => 'link_to',
				'type' => 'radio',
				'instructions' => 'Select the type of link',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'internal_page' => 'Internal Page',
					'internal' => 'Internal',
					'external' => 'External',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'internal_page',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_5907af8e518d2',
				'label' => 'Internal Page',
				'name' => 'internal_page',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5907ae47518cf',
							'operator' => '==',
							'value' => 'internal_page',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array (
				),
				'taxonomy' => array (
				),
				'allow_null' => 0,
				'allow_archives' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5907aee0518d0',
				'label' => 'Link Url',
				'name' => 'link_url',
				'type' => 'url',
				'instructions' => 'Enter the full destination Url',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5907ae47518cf',
							'operator' => '==',
							'value' => 'external',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_5907af54518d1',
				'label' => 'Relative Url',
				'name' => 'relative_url',
				'type' => 'text',
				'instructions' => 'Include only the part of the url that comes after the domain name.<br>
ie. if you want to link to the root of the site just enter "/" as the link.<br>
<b>Note:</b>This is useful if extra query parameters need to be entered through the url.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_5907ae47518cf',
							'operator' => '==',
							'value' => 'internal',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '/',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 0,
		'description' => '',
		'modified' => 1493676733,
	));

	acf_add_local_field_group(array (
		'key' => 'group_5907b0f9e89aa',
		'title' => 'Template - Text Link',
		'fields' => array (
			array (
				'key' => 'field_5907b107ab1d0',
				'label' => 'Link Text',
				'name' => 'link_text',
				'type' => 'text',
				'instructions' => 'Enter the text to be clicked on for the link.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5907b132ab1d1',
				'label' => 'Link Cloned',
				'name' => 'link_cloned',
				'type' => 'clone',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'clone' => array (
					0 => 'group_5907ae157e336',
				),
				'display' => 'seamless',
				'layout' => 'block',
				'prefix_label' => 0,
				'prefix_name' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 0,
		'description' => '',
		'modified' => 1493676766,
	));

	acf_add_local_field_group(array (
		'key' => 'group_58d9847db835f',
		'title' => 'BYU Footer',
		'fields' => array (
			array (
				'key' => 'field_58d984a127ca3',
				'label' => 'BYU Footer Navigation',
				'name' => 'byu_footer_navigation',
				'type' => 'true_false',
				'instructions' => 'Check this box if you would like additional links to appear in your footer about the BYU footer ribbon.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array (
				'key' => 'field_58d9851e27ca4',
				'label' => 'BYU Footer Columns',
				'name' => 'byu_footer_columns',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_58d984a127ca3',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'button_label' => 'Add Column',
				'min' => 1,
				'max' => 4,
				'layouts' => array (
					array (
						'key' => '58d9852b85215',
						'name' => 'column_content',
						'label' => 'Column Content',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_58d988174a5f1',
								'label' => 'Column Header',
								'name' => 'column_header',
								'type' => 'text',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58dbfaf411355',
								'label' => 'Column Rows',
								'name' => 'column_rows',
								'type' => 'flexible_content',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'button_label' => 'Add Row',
								'min' => '',
								'max' => '',
								'layouts' => array (
									array (
										'key' => '58dbfb05f319d',
										'name' => 'social_media',
										'label' => 'Social Media',
										'display' => 'block',
										'sub_fields' => array (
											array (
												'key' => 'field_58d9862f27caa',
												'label' => 'Social Media Links',
												'name' => 'social_media_links',
												'type' => 'flexible_content',
												'instructions' => 'Select the social media icons you would like to include',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'button_label' => 'Add Social Icon',
												'min' => 1,
												'max' => '',
												'layouts' => array (
													array (
														'key' => '58d9864ab767d',
														'name' => 'instagram',
														'label' => 'Instagram',
														'display' => 'block',
														'sub_fields' => array (
															array (
																'key' => 'field_58d9865427cab',
																'label' => 'url',
																'name' => 'url',
																'type' => 'url',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array (
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => '',
																'placeholder' => '',
															),
														),
														'min' => '',
														'max' => '1',
													),
													array (
														'key' => '58dbfb9ff5ffb',
														'name' => 'twitter',
														'label' => 'Twitter',
														'display' => 'block',
														'sub_fields' => array (
															array (
																'key' => 'field_58d9866027cac',
																'label' => 'url',
																'name' => 'url',
																'type' => 'url',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array (
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => '',
																'placeholder' => '',
															),
														),
														'min' => '',
														'max' => '1',
													),
													array (
														'key' => '58dbfbc1f5ffc',
														'name' => 'facebook',
														'label' => 'Facebook',
														'display' => 'block',
														'sub_fields' => array (
															array (
																'key' => 'field_58d9866927cad',
																'label' => 'url',
																'name' => 'url',
																'type' => 'url',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array (
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => '',
																'placeholder' => '',
															),
														),
														'min' => '',
														'max' => '1',
													),
													array (
														'key' => '58dbfbdaf5ffd',
														'name' => 'youtube',
														'label' => 'Youtube',
														'display' => 'block',
														'sub_fields' => array (
															array (
																'key' => 'field_58d9868e27caf',
																'label' => 'url',
																'name' => 'url',
																'type' => 'url',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array (
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => '',
																'placeholder' => '',
															),
														),
														'min' => '',
														'max' => '1',
													),
													array (
														'key' => '58dbfbf5f5ffe',
														'name' => 'google_plus',
														'label' => 'Google Plus',
														'display' => 'block',
														'sub_fields' => array (
															array (
																'key' => 'field_58d9867b27cae',
																'label' => 'url',
																'name' => 'url',
																'type' => 'url',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array (
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => '',
																'placeholder' => '',
															),
														),
														'min' => '',
														'max' => '1',
													),
													array (
														'key' => '58e2bf191cee1',
														'name' => 'linkedin',
														'label' => 'LinkedIn',
														'display' => 'block',
														'sub_fields' => array (
															array (
																'key' => 'field_58e2bf191cee2',
																'label' => 'url',
																'name' => 'url',
																'type' => 'url',
																'instructions' => '',
																'required' => 0,
																'conditional_logic' => 0,
																'wrapper' => array (
																	'width' => '',
																	'class' => '',
																	'id' => '',
																),
																'default_value' => '',
																'placeholder' => '',
															),
														),
														'min' => '',
														'max' => '1',
													),
												),
											),
										),
										'min' => '',
										'max' => '',
									),
									array (
										'key' => '58dbfb1711356',
										'name' => 'action_button',
										'label' => 'Action Button',
										'display' => 'block',
										'sub_fields' => array (
											array (
												'key' => 'field_58dc05f52327e',
												'label' => 'Button Label',
												'name' => 'button_label',
												'type' => 'text',
												'instructions' => '',
												'required' => 1,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array (
												'key' => 'field_58e7e70a04fe7',
												'label' => 'Type',
												'name' => 'type',
												'type' => 'radio',
												'instructions' => 'Select the type of link',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array (
													'internal' => 'Internal',
													'external' => 'External',
												),
												'allow_null' => 0,
												'other_choice' => 0,
												'save_other_choice' => 0,
												'default_value' => 'Internal',
												'layout' => 'vertical',
												'return_format' => 'value',
											),
											array (
												'key' => 'field_58e7e71904fe8',
												'label' => 'Url',
												'name' => 'url',
												'type' => 'url',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_58e7e70a04fe7',
															'operator' => '==',
															'value' => 'external',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
											),
											array (
												'key' => 'field_58e7e73204fe9',
												'label' => 'Relative Url',
												'name' => 'relative_url',
												'type' => 'text',
												'instructions' => 'Include only the part of the url that comes after the domain name.<br>
ie. if you want to link to the root of the site just enter "/" as the link.',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_58e7e70a04fe7',
															'operator' => '==',
															'value' => 'internal',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '/',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
										),
										'min' => '',
										'max' => '',
									),
									array (
										'key' => '58dbfb2f11357',
										'name' => 'link',
										'label' => 'Link',
										'display' => 'block',
										'sub_fields' => array (
											array (
												'key' => 'field_58dc068e2327f',
												'label' => 'Text',
												'name' => 'text',
												'type' => 'text',
												'instructions' => '',
												'required' => 1,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array (
												'key' => 'field_58e7e240c8b08',
												'label' => 'Type',
												'name' => 'type',
												'type' => 'radio',
												'instructions' => 'Select the type of link',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array (
													'internal' => 'Internal',
													'external' => 'External',
												),
												'allow_null' => 0,
												'other_choice' => 0,
												'save_other_choice' => 0,
												'default_value' => 'Internal',
												'layout' => 'vertical',
												'return_format' => 'value',
											),
											array (
												'key' => 'field_58e7e295c8b09',
												'label' => 'Url',
												'name' => 'url',
												'type' => 'url',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_58e7e240c8b08',
															'operator' => '==',
															'value' => 'external',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
											),
											array (
												'key' => 'field_58e7e2bdc8b0a',
												'label' => 'Relative Url',
												'name' => 'relative_url',
												'type' => 'text',
												'instructions' => 'Include only the part of the url that comes after the domain name.<br>
ie. if you want to link to the root of the site just enter "/" as the link.',
												'required' => 0,
												'conditional_logic' => array (
													array (
														array (
															'field' => 'field_58e7e240c8b08',
															'operator' => '==',
															'value' => 'internal',
														),
													),
												),
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '/',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
										),
										'min' => '',
										'max' => '',
									),
									array (
										'key' => '58dc0aa3a4075',
										'name' => 'info_text',
										'label' => 'Info Text',
										'display' => 'block',
										'sub_fields' => array (
											array (
												'key' => 'field_58dc0aaca4076',
												'label' => 'Text',
												'name' => 'text',
												'type' => 'textarea',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array (
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'maxlength' => '',
												'rows' => '',
												'new_lines' => 'br',
											),
										),
										'min' => '',
										'max' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'site_options',
				),
			),
		),
		'menu_order' => 5,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1491594649,
	));

	acf_add_local_field_group(array (
		'key' => 'group_5902479ea6323',
		'title' => 'Grid Options',
		'fields' => array (
			array (
				'key' => 'field_59025ac903fbf',
				'label' => 'Grid Selection',
				'name' => 'grid_selection',
				'type' => 'radio',
				'instructions' => 'Choose the grid that you would like to use. \'Default\' is the standard grid included with the standard framework parent theme. \'Custom\' refers to the selection found in \'Settings->Generate Grid\'. Choose \'None\' if you don\'t want the overhead of a grid and want to do complete custom work.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'default' => 'Default',
					'custom' => 'Custom',
					'none' => 'None',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_59024d0401638',
				'label' => 'Where To Use Grid Overlay',
				'name' => 'where_to_use_grid_overlay',
				'type' => 'radio',
				'instructions' => 'Choose which site-domains the grid overlay to be used on. If \'All\' is chosen then the overlay will be used on any domain. \'Choose Domains\' becomes useful if you have multiple versions of your site (such as production and development) and you want to use the grid for development but not let it be seen on production sites.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_59025ac903fbf',
							'operator' => '!=',
							'value' => 'none',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'all' => 'All Domains',
					'choose' => 'Choose Domains',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'all',
				'layout' => 'vertical',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_590247be01636',
				'label' => 'Grid Overlay Domains',
				'name' => 'grid_overlay_domains',
				'type' => 'repeater',
				'instructions' => 'Add all the domains you want the grid overlay to be available on.',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_59024d0401638',
							'operator' => '==',
							'value' => 'choose',
						),
						array (
							'field' => 'field_59025ac903fbf',
							'operator' => '!=',
							'value' => 'none',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add Domain',
				'sub_fields' => array (
					array (
						'key' => 'field_59024c9b01637',
						'label' => 'Domain',
						'name' => 'domain',
						'type' => 'text',
						'instructions' => 'enter the domain name.<br>
ie. \'speeches.byu.edu\'',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'site_options',
				),
			),
		),
		'menu_order' => 10,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1493326745,
	));

	acf_add_local_field_group(array (
		'key' => 'group_58e80495c59dc',
		'title' => 'Search and Analytics Codes',
		'fields' => array (
			array (
				'key' => 'field_58e804d8577fa',
				'label' => 'Search Codes',
				'name' => 'search_codes',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'button_label' => 'Add Search Code',
				'min' => '',
				'max' => '',
				'layouts' => array (
					array (
						'key' => '58e804e195c70',
						'name' => 'google_code',
						'label' => 'Google Code',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_58e80504577fb',
								'label' => 'code',
								'name' => 'code',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58e80796577fd',
								'label' => 'Use On Specific Domain',
								'name' => 'use_on_specific_domain',
								'type' => 'radio',
								'instructions' => 'Choose which site-domains this code is to be used on. If \'All\' is chosen then this code will be used on any domain. \'Choose Domains\' becomes useful if you have multiple versions of your site (such as production and development) and you want to use a distinct code for each site.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'all' => 'All Domains',
									'choose' => 'Choose Domains',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'all',
								'layout' => 'vertical',
								'return_format' => 'value',
							),
							array (
								'key' => 'field_58e80769577fc',
								'label' => 'Domains',
								'name' => 'domains',
								'type' => 'repeater',
								'instructions' => 'Add all the domains you want this code to be used for.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_58e80796577fd',
											'operator' => '==',
											'value' => 'choose',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 1,
								'max' => 0,
								'layout' => 'table',
								'button_label' => 'Add Domain',
								'sub_fields' => array (
									array (
										'key' => 'field_58e8093e577fe',
										'label' => 'Domain',
										'name' => 'domain',
										'type' => 'text',
										'instructions' => 'enter the domain name.<br>
ie. \'speeches.byu.edu\'',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
			),
			array (
				'key' => 'field_58e809aa577ff',
				'label' => 'Analytics Codes',
				'name' => 'analytics_codes',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'button_label' => 'Add Analytics Code',
				'min' => '',
				'max' => '',
				'layouts' => array (
					array (
						'key' => '58e804e195c70',
						'name' => 'google_code',
						'label' => 'Google Code',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_58e809aa57800',
								'label' => 'code',
								'name' => 'code',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58e809aa57801',
								'label' => 'Use On Specific Domain',
								'name' => 'use_on_specific_domain',
								'type' => 'radio',
								'instructions' => 'Choose which site-domains this code is to be used on. If \'All\' is chosen then this code will be used on any domain. \'Choose Domains\' becomes useful if you have multiple versions of your site (such as production and development) and you want to use a distinct code for each site.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'all' => 'All Domains',
									'choose' => 'Choose Domains',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'all',
								'layout' => 'vertical',
								'return_format' => 'value',
							),
							array (
								'key' => 'field_58e809aa57802',
								'label' => 'Domains',
								'name' => 'domains',
								'type' => 'repeater',
								'instructions' => 'Add all the domains you want this code to be used for.',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_58e809aa57801',
											'operator' => '==',
											'value' => 'choose',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 1,
								'max' => 0,
								'layout' => 'table',
								'button_label' => 'Add Domain',
								'sub_fields' => array (
									array (
										'key' => 'field_58e809aa57803',
										'label' => 'Domain',
										'name' => 'domain',
										'type' => 'text',
										'instructions' => 'enter the domain name.<br>
ie. \'speeches.byu.edu\'',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array (
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'site_options',
				),
			),
		),
		'menu_order' => 10,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
		'modified' => 1491602161,
	));

endif;